---

base_locale: en
locales: [en]

ignore_unused:
  - "decidim.components.extra_user_fields.name"
  - activemodel.attributes.user.*
  - decidim.admin.extra_user_fields.menu.title
  - decidim.extra_user_fields.genders.*

ignore_missing:
  - decidim.participatory_processes.scopes.global
